version: '3'

services:
  edge:
    build: ./edge
    container_name: edge
    ports:
      - "8080:80"
    command: /bin/bash -c "envsubst '' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
  
  sharder:
    build: ./sharder
    container_name: sharder
    volumes:
      #- /Users/iana/sharder/sharder.yml:/srv/sharder/sharder.yml:ro
      - /Users/iana/sharder/sharder.yml:/srv/sharder/sharder.yml:ro
      - /Users/iana/sharder/sharder.db:/srv/sharder/sharder.db
    ports:
      - "8888:8888"
    environment:
      - DB_TYPE=sqlite

