version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: edge
    ports:
      - "8080:80"
  
  sharder:
    build: ./sharder
    container_name: sharder
    ports:
      - "8888:8888"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python3.6", "/srv/hubsharder/request_sharder.py"]

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
